### ISSUE TITLE
Unable to authorize (Windows 7)

### ISSUE THREAD

**Issue by ThomasPontoppidan** [flickr-downloadr/flickr-downloadr-gtk#27]
When I launch Flickr Downloadr and try to login, I get the Flickr authorization page, but when I accept I get a "page cannot be displayed" on a localhost address http://localhost:47654/?oauth_token=XXXXXXXXXXXXXXXXXXXXXXXXXXX&oauth_verifier=xxxxxxxxxxx

**Comment by floydpink** [comment]
Thank you for raising the issue. 

Could you please help us troubleshoot the issue by setting the Log Level to `ALL` in the Preferences window and posting the log after restarting the app and reproducing the error?

By default the logs reside here: `%USERPROFILE%\AppData\Roaming\flickr-downloadr\Logs\` - but that is also customizable using the Log Location setting.

**Comment by ThomasPontoppidan** [comment]
I would, but I can't find the preferences window - only the login window?

Best regards,
Thomas

2015-08-13 17:01 GMT+02:00 Hari Menon <notifications@github.com>:

**Comment by floydpink** [comment]
Ah, yes - my apologies.

Preferences are set only after the first login and since you have issue in the login flow itself, you would not see the Preferences window.

Please edit this file using a text editor like Notepad: `C:\Program Files (x86)\flickrdownloadr\flickrdownloadr.log4net` and change the line that reads `<level value="INFO" />` to `<level value="ALL" />` and then restart the app.

And after you encounter the issue with authentication, please post the contents of the log file at `%USERPROFILE%\AppData\Roaming\flickr-downloadr\Logs\flickrdownloadr.log`

**Comment by ThomasPontoppidan** [comment]
I changed the config (had to change permissions on the file) and reran, but
I don't get a log. All that is at the location specified is another config
file (identical to the first). i changed that one in the same way but still
don't get a log.

Could it be a permission issue in Windows 7?

Best regards,
Thomas Pontoppidan


2015-08-13 18:30 GMT+02:00 Hari Menon <notifications@github.com>:

**Comment by floydpink** [comment]
Not sure if it could be a permission issue. 

If you're familiar using the [Process Monitor tool](https://technet.microsoft.com/en-us/Library/bb896645.aspx?f=255&MSPPError=-2147217396) from Microsoft, we could observe the application process and get to the root cause on why it is not able to even create the logs.

**Comment by ThomasPontoppidan** [comment]
Sorry, too advanced for me! I will look around for other options instead:-(

2015-08-17 18:52 GMT+02:00 Hari Menon <notifications@github.com>:

**Comment by nousename** [comment]
Windows 10 same problem, latest version.
Try to authorize yahoo/flickr and get taken to this page
http://localhost:64469/?oauth_token=72157676040675712-8475ff31ad61c832&oauth_verifier=6073a10b421621ef

**Comment by floydpink** [comment]
> Windows 10 same problem, latest version.
> Try to authorize yahoo/flickr and get taken to this page
> http://localhost:64469/?oauth_token=72157676040675712-8475ff31ad61c832&oauth_verifier=6073a10b421621ef

@nousename - That is the page that confirms that you have successfully authenticated - can you tell me if the app shows you as logged in when the browser window opens this page?

**Comment by nousename** [comment]
No the app just remains "spinning" on waiting for authorization, and never goes any further

**Comment by nousename** [comment]
When I reach the page cannot be displayed, and click on fix connection(out of curiosity)
I get the windows network diagnostic of 
"The remote device or resource won't accept the connection"
