### ISSUE TITLE
Download of album with 169 pictures only downloads 123

### ISSUE THREAD

**Issue by kahukowhai** [flickr-downloadr/flickr-downloadr-gtk#48]
In Flickr's user interface the album says it has 169 pictures. Flickr-downloadr when going into the album then selecting it for download says there is 169 photos and clicking All Pages to download says  to confirm you want to download 169 pictures. However on two separate attempts only 123 pictures are downloaded.

**Comment by kahukowhai** [comment]
A careful comparison of the original Flickr album and the 123 pictures downloaded revealed 46 duplicate pictures on Flickr.
If the software is designed specifically to eliminate duplicate pictures on download, it should display a warning to this effect so as to eliminate confusion over the discrepancy.

**Comment by floydpink** [comment]
Thanks for creating the issue

I wasn't aware of the scenario that photos with duplicate titles on flickr can overwrite the previously downloaded ones (and I am assuming the default preference to save the photos with their title as the filename is in play).

And the fact that there could be multiple, distinct photos all titled the same - if that is indeed what is happening - there could be loss of images too.

Will look into getting this fixed by appending an auto-generated tie-breaker into the file names.

**Comment by kahukowhai** [comment]
Yes I have saving files with their title in effect.

In this case, deduplicating the files is a welcome factor to come into 
play. Flickr by default allows the same filename to be uploaded multiple 
times and added to the same set, which is annoying as there is no built 
in mechanism for identifying duplicates.

**Comment by robermann** [comment]
The fix for #52 should close also this issue.

**Comment by robermann** [comment]
(the commit 3748c67 should have fixed this bug - if so, close the ticket)
