### ISSUE TITLE
build error Source file `../Secrets.cs' could not be found

### ISSUE THREAD

**Issue by zhou0** [flickr-downloadr/flickr-downloadr-gtk#67]
/usr/home/lzhou/github.com/flickr-downloadr/flickr-downloadr-gtk/archive/flickr-downloadr-gtk-2.2.0.1/source/FloydPink.Flickr.Downloadr.Bootstrap/CSC: Error CS2001: Source file `../Secrets.cs' could not be found (CS2001) (FloydPink.Flickr.Downloadr.Bootstrap)

**Comment by floydpink** [comment]
That file includes the API key that this application uses to enable OAuth authentication against Flickr- please let us know if you’d still like to get a copy of Secret.cs set up yourself so that you can build and run without the installers. 

Also, there’s a new version now available that might work for you - you may want to check that out

**Comment by floydpink** [comment]
See https://github.com/flickr-downloadr/flickr-downloadr-gtk/issues/82#issuecomment-436119409
